### PR TITLE
Responsive for mobile screen solved.

### LINKED ISSUE #1: Not Responsive for mobile screens
This website isnt responsive in mobile screens,If someone is intrested to fix that, can contribute here

### PR DESCRIPTION
**Pull request by Rishav1707**
### This PR fixes the following issues:-
closes #1 
### Changes made:-

- Adding CSS media query to the moon.css file.
### Before
Screenshot 2022-12-13 171114
### After
Screenshot 2022-12-13 171229

### CODE REVIEW

**Comment by abhinav2712** [comment]
@Rishav1707 It looks like you have removed the other items(earth,mars..) in nav bar, can you tell if you have made them into the "hamp burger" option as well?

**Comment by Rishav1707** [comment]
No, I have not made the hamburger option.
I only worked on responsiveness in mobile view.
@abhinav2712

**Comment by Rishav1707** [comment]
The navbar items were not removed, I hide the navbar items in mobile view.
It will shown up after the screen crossed 600px.

**Comment by abhinav2712** [comment]
@Rishav1707 If possible, make the hamburger option, would be a great practice for you, take a day or two!
Happy hacking!

**Comment by Rishav1707** [comment]
OK @abhinav2712

**Comment by Rishav1707** [comment]
Screenshot 2022-12-14 164511
@abhinav2712 Hamburger option is added to the mobile screen.

**Review by abhinav2712 — APPROVED** [review]
Seems good, Well done!

**Comment by abhinav2712** [comment]
@Rishav1707 Great work! Your PR has been merged to the master, feel free to point out more issues and work on it if you want, till then I will see what more enhancements we can make to it.
Happy Hacking!

**Comment by Rishav1707** [comment]
Thank you @abhinav2712

**Pull request merged**
